spring:
  application:
    name: demo
#  aop:
#      proxy-target-class: true
#      auto: true
  profiles: test
server:
  port: 8080
logging:
  config: classpath:log4j2-spring-test.xml


management:
  endpoints:
    web:
      exposure:
        include: '*'
      base-path: /
port: 22222222



feign:
  hystrix:
    enabled: true

#hystrix配置reference: https://github.com/Netflix/Hystrix/wiki/Configuration
#TODO 根据具体业务和需要做降级和熔断配置
hystrix:
  threadpool:
    default:
      coreSize: 10
    remoteFinanceClient: #clentName
      coreSize: 10
  command:
    default:
      coreSize: 4
      maximumSize: 5
      allowMaximumSizeToDivergeFromCoreSize: true
      maxQueueSize: 50000
      queueSizeRejectionThreshold: 50000
      execution:
        isolation: #隔离
          thread:
            timeoutInMilliseconds: 20000 #默认为1000调大 线程超时时间
      circuitBreaker:
        requestVolumeThreshold: 20 #默认为20
        sleepWindowsInMilliseconds: 5000 #默认为5000 断路器打开后的休眠时间
        errorThresholdPercentage: 60 #默认为50 错误比例
      metrices:
        rollingStats:
          timeInMilliseconds: 300000 #默认10000 统计的时间窗口

#logging:
#  config: classpath:log4j2.yml









